version: "3.9"

services:
  node:
    image: rocketpool/smartnode:v1.11.0
    environment:
      - ENV=/root/.profile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - rocketpool-data:/.rocketpool
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        rm /.dockerenv
        mv /go/bin/rocketpool /go/bin/rocketpoold
        apk update
        apk add docker-cli
        wget https://github.com/rocket-pool/smartnode-install/releases/latest/download/rocketpool-cli-linux-amd64 -O /usr/local/bin/rocketpool
        chmod +x /usr/local/bin/rocketpool 
        echo 'alias rp="rocketpool -d /go/bin/rocketpoold -c /.rocketpool --allow-root"' >/root/.profile
        mkdir -p /.rocketpool/data
        exec /go/bin/rocketpoold node
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: ["node.role == manager"]
      resources:
        reservations:
          memory: 50M

  watchtower:
    image: rocketpool/smartnode:v1.11.0
    command: watchtower
    volumes:
      - rocketpool-data:/.rocketpool
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: ["node.role == worker"]

  validator:
    image: sigp/lighthouse:latest
    volumes:
      - rocketpool-data:/.rocketpool
    entrypoint:
      - lighthouse
      - vc
      - --datadir
      - /.rocketpool/data/validators/lighthouse
      - --init-slashing-protection
      - --beacon-nodes
      - https://goerlicl-a.example.com,https://goerlicl-b.example.com
      - --graffiti
      - "RP Lighthouse"
      - --network
      - prater
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: ["node.role == worker"]
    
  haproxy:
    image: haproxy:latest
    user: root
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y curl jq bc ca-certificates
        haproxy -f /usr/local/etc/haproxy/haproxy.cfg
    networks:
      default:
        aliases:
          - goerliws-lb.example.com
          - goerli-lb.example.com
          - goerlicl-lb.example.com
    configs:
      - source: goerli-haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
      - source: check-ecsync.sh
        target: /var/lib/haproxy/check-ecsync.sh
        mode: 0555
      - source: check-ccsync.sh
        target: /var/lib/haproxy/check-ccsync.sh
        mode: 0555
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: ["node.role == worker"]
    healthcheck:
      test: curl -sS http://localhost:8405/metrics || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

configs:
  goerli-haproxy.cfg:
    external: true
  check-ecsync.sh:
    external: true
  check-ccsync.sh:
    external: true

volumes:
  rocketpool-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=MYADDR.efs.us-east-2.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: "MYADDR.efs.us-east-2.amazonaws.com:/rocketpool"
